<?php

declare(strict_types=1);

namespace Lettr\Laravel\Support;

/**
 * Shared pieces of generated PHP: the class docblock that marks a file as
 * generated, and a sorted import block.
 */
final class GeneratedCode
{
    /**
     * A class docblock saying what the class is, which command generated it,
     * and that running the command again overwrites the file.
     */
    public static function docblock(string $description, string $command, string $advice): string
    {
        $lines = [
            ...self::wrap($description),
            '',
            ...self::wrap("Generated by {$command}. Running it again overwrites this file, so {$advice}"),
        ];

        return "/**\n".implode("\n", array_map(fn (string $line): string => rtrim(' * '.$line), $lines))."\n */";
    }

    /**
     * Wrap text to docblock width without breaking inside `code spans`.
     *
     * @return array<int, string>
     */
    private static function wrap(string $text): array
    {
        $protected = (string) preg_replace_callback('/`[^`]*`/', fn (array $m): string => str_replace(' ', "\0", $m[0]), $text);

        return explode("\n", str_replace("\0", ' ', wordwrap($protected, 74)));
    }

    /**
     * `use` statements for the given classes, sorted the way Laravel's own
     * generators sort them, skipping classes already in $namespace.
     *
     * @param  array<int, string>  $classes
     */
    public static function imports(string $namespace, array $classes): string
    {
        $classes = array_filter(
            array_unique($classes),
            fn (string $class): bool => substr($class, 0, (int) strrpos($class, '\\')) !== $namespace,
        );

        usort($classes, fn (string $a, string $b): int => strcasecmp($a, $b));

        return implode("\n", array_map(fn (string $class): string => "use {$class};", $classes));
    }
}
